### ISSUE TITLE
设置阈值为95时，到80仍停止充电

### ISSUE THREAD

**Issue by Wtrwx** [lich4/AlDente#20]
这几个版本一直没修复，原因未知

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by lich4** [comment]
安装新版本需要卸载掉老的，且注意关闭系统设置“优化电池充电”。
下一版本将会自动化

**Comment by Wtrwx** [comment]
感谢您，未关闭系统优化电池充电

**Comment by hezz79** [comment]
I had the same issue too. I’d set the limit to 80% and charging stopped there. Later on I changed the limit to 95% but the battery still stayed at 80, so I updated to v1.2 and restarted my device & only then did it charge to 95%. I will keep monitoring to see if the issue is solved or not. Also, can we get to set % to any value instead of being locked to only 5% increments in the next update?

**Comment by lich4** [comment]
> I had the same issue too. I’d set the limit to 80% and charging stopped there. Later on I changed the limit to 95% but the battery still stayed at 80, so I updated to v1.2 and restarted my device & only then did it charge to 95%. I will keep monitoring to see if the issue is solved or not. Also, can we get to set % to any value instead of being locked to only 5% increments in the next update?

Yes, but it hard to put 20%-100% to progress bar, while step of 5% is much easier. I thought accuracy of 1% is meaningless, so I set it to 5%

**Comment by lich4** [comment]
> I had the same issue too. I’d set the limit to 80% and charging stopped there. Later on I changed the limit to 95% but the battery still stayed at 80, so I updated to v1.2 and restarted my device & only then did it charge to 95%. I will keep monitoring to see if the issue is solved or not. Also, can we get to set % to any value instead of being locked to only 5% increments in the next update?

As some research shows, capacity between 20%-80% is best for battery health, so It's not recommended to set max threshhold above 80%.

**Comment by lich4** [comment]
Fixed in v1.3.
1.3版已修复
